# this script was written as a part of springer bookchapter titled 
# "Incorporating sequence-dependent DNA shape and dynamics into 
# transcriptome data analysis"
# Authors: Manisha Kalsan, Almas Jabeen, Shandar Ahmad
# Affiliation: School of Computational and Integrative Sciences, 
# Jawaharlal Nehru University, Delhi, India
# Email: shandar@jnu.ac.in
# 
# This script uses DNA shape profiles generated by dna_shape_analysis.R for 
# visualization
# 
# 
# 

num_datasets<-2
seq_length<-20

plot_data_names<-c("unregulated","regulated")
list_pos_mean<-system("ls pos_mean*",intern=T)
tf_reg_shape_means<-read.table("pos_mean_5bin_dna_shape_remaining_genes_flank",header=T)
remaining_shape_means<-read.table("pos_mean_5bin_dna_shape_tf_reg_genes_flank",header=T)

pdf("plots_promoters_shape.pdf")
par(mfrow=c(2,2))
x_ticks<-seq(0,seq_length-4,2)[-1]
x_labels<-seq(-(seq_length-4),1,2)[-1]
width<-3
for(i in 1:13){
   data_a<-filter(as.numeric(remaining_shape_means[,i]),filter = rep(1, width)) / width
   data_b<-filter(as.numeric(tf_reg_shape_means[,i]),filter = rep(1, width)) / width
   min<-min(remaining_shape_means[,i],tf_reg_shape_means[,i])
   max<-max(remaining_shape_means[,i],tf_reg_shape_means[,i])
   plot(as.numeric(data_a),xlab="position",xaxt="n",yaxt="n", main="Comparison of DNA shape profiles",
        cex.main=1,type="l",ylab=params[i],col="red",lwd=3,ylim=c(min,max),cex.sub=0.8,
        sub="Promoter regions of DEGs regulated by TF SP1 and those not regulated")
   axis(1,at=x_ticks,labels=x_labels,cex.axis=0.8) #x axis labels
   axis(2,cex.axis=0.7,cex.lab=0.8,las=1) #y axis labels
   lines(as.numeric(data_b),col="green",type="l",lwd=3)# adding other data lines
   legend("bottomright",legend=plot_data_names,bty="n",pch=c(19,19),
          col=c("red","green"),cex=0.8)
}
dev.off()

#boxplot of average values of static parameters
pdf("plots_promoters_shape_boxplots.pdf")
par(mfrow=c(2,2))
for(i in 1:13){
   min_y<-min(remaining_shape_means[,i],tf_reg_shape_means[,i])
   max_y<-max(remaining_shape_means[,i],tf_reg_shape_means[,i])
   boxplot(list(as.numeric(remaining_shape_means[,i]),as.numeric(tf_reg_shape_means[,i])), 
           cex.main=1,ylab=params[i],col=c("coral","green4"),ylim=c(min_y,max_y),cex.sub=0.8,
           names = plot_data_names)
}
dev.off()


#boxplots for ensemble data
dna_shape_files<-system("ls 5bin_dna_shape_*",intern=T)
num_bins<-as.numeric(5)
num_datasets<-as.numeric(2)
data_variable_names<-c(paste("data",1:num_datasets,sep="_"))

# assign the shape profiles to variable names
for (i in 1:length(data_variable_names)) {
   assign(data_variable_names[i], read.table(dna_shape_files[i],header=T))
}

ticks<-seq(0,num_datasets*5,num_datasets)
tick_diff<-(ticks[2]-ticks[1])/(num_datasets+1)
data_ticks<-lapply(2:length(ticks), function(x){
   c(ticks[x-1]+tick_diff,ticks[x]-tick_diff)
})
data_ticks<-unlist(data_ticks)

pdf("ensemble_boxplots_5bin.pdf")
par(mfrow=c(2,2))
par_col<-seq(14,13+(13*num_bins),5)
for(i in 1:13){
   par_data<-lapply(1:num_datasets,function(j){
      get(data_variable_names[j])[,(par_col[i]:(par_col[i]+4))]
   })
   min_y<-min(par_data[[1]],par_data[[2]])
   max_y<-max(par_data[[1]],par_data[[2]])
   boxplot(list(par_data[[1]][,1],par_data[[2]][,1],
                par_data[[1]][,2],par_data[[2]][,2],
                par_data[[1]][,3],par_data[[2]][,3],
                par_data[[1]][,4],par_data[[2]][,4],
                par_data[[1]][,5],par_data[[2]][,5]),
           ylim=c(min_y,max_y),col=c("coral","green4"), ylab=params[i], 
           xlab="ensemble bins",xaxt="n", at=data_ticks,boxwex=0.5)
   axis(1,at=seq(1,num_datasets*5,num_datasets),labels=c("bin 1", "bin 2", "bin 3", "bin 4", "bin 5"))
   legend("topright",legend=plot_data_names,col=c("coral","green4"), 
          pch=c(20,20),cex=0.55)
}
dev.off()


